    /*  charAt()
        concat()
        contains()
        indexOf()
        length()
        search()
        slice()
        split()
        sub()
        substr()
        toLowerCase()
        toUpperCase()*/